### PR TITLE
Expand permutations

### PR DESCRIPTION
**Pull request by jakewarren**
Expands the permutation list by combining a variety of community wordlists. Also removes permutations with underscores.

I know multiple commits are usually squashed in a PR however I gave credit to each source in my commit messages so I didn't want to squash them.

Opening it up for discussion - since this wordlist is significantly larger it may be better to move into a separate `permutations-large.json` file.

### CODE REVIEW

**Comment by bbb31** [comment]
I would definitely accept a `permutations-large.json` PR.

**Comment by jakewarren** [comment]
@bbb31 I moved the list to `permutations-large.json` and restored `permutations.json` with the version in master.

**Comment by bbb31** [comment]
It looks like you're still modifying `permutations.json`.

**Comment by jakewarren** [comment]
Sorry, yeah it did look that way since my branch had started off an older commit prior to the previous PR and each of my commits was adding the permutations to `permutations.json`.  

I did double check that the MD5 matched on both versions. :) However I get that it doesn't look good. To clean that up I rebased on master.

**Comment by bbb31** [comment]
Also, curious why:

> Also removes permutations with underscores.

Is it because of [AWS S3](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html) naming conventions?  

I plan on adding in the summer domain enumeration which would definitely use that. Since the `permutations` list is growing; no sense in not applying it to other locations where enumeration is key.

**Comment by menzow** [comment]
Hey @bbb31, about the underscores; I mentioned this on a earlier PR here: https://github.com/bbb31/slurp/pull/15#issuecomment-368933356 . I'm also gathering statistics on hit rates for each permutation (~100m buckets scanned). May be useful to format lists based on that.

**Pull request merged**
